<function parse_eccv at 0x7f2cf009b2e0> 2027
<function parse_eccv at 0x7f2cf009b2e0> 2026
Traceback (most recent call last):
  File "/data/cloud/Programming/aideadlines/./src/update_data.py", line 173, in <module>
    yearly_datas = conf_parser(year)
  File "/data/cloud/Programming/aideadlines/src/parser/common_website.py", line 155, in parse_eccv
    data = parse_common_website_format(data, url + "Dates")
  File "/data/cloud/Programming/aideadlines/src/parser/common_website.py", line 7, in parse_common_website_format
    website = requests.get(url)
  File "/data/cloud/Programming/aideadlines/venv/lib64/python3.13/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/data/cloud/Programming/aideadlines/venv/lib64/python3.13/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/cloud/Programming/aideadlines/venv/lib64/python3.13/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/data/cloud/Programming/aideadlines/venv/lib64/python3.13/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/data/cloud/Programming/aideadlines/venv/lib64/python3.13/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
        method=request.method,
    ...<9 lines>...
        chunked=chunked,
    )
  File "/data/cloud/Programming/aideadlines/venv/lib64/python3.13/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    response = self._make_request(
        conn,
    ...<10 lines>...
        **response_kw,
    )
  File "/data/cloud/Programming/aideadlines/venv/lib64/python3.13/site-packages/urllib3/connectionpool.py", line 464, in _make_request
    self._validate_conn(conn)
    ~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/data/cloud/Programming/aideadlines/venv/lib64/python3.13/site-packages/urllib3/connectionpool.py", line 1093, in _validate_conn
    conn.connect()
    ~~~~~~~~~~~~^^
  File "/data/cloud/Programming/aideadlines/venv/lib64/python3.13/site-packages/urllib3/connection.py", line 704, in connect
    self.sock = sock = self._new_conn()
                       ~~~~~~~~~~~~~~^^
  File "/data/cloud/Programming/aideadlines/venv/lib64/python3.13/site-packages/urllib3/connection.py", line 198, in _new_conn
    sock = connection.create_connection(
        (self._dns_host, self.port),
    ...<2 lines>...
        socket_options=self.socket_options,
    )
  File "/data/cloud/Programming/aideadlines/venv/lib64/python3.13/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
    ~~~~~~~~~~~~^^^^
KeyboardInterrupt
